### ISSUE TITLE
Update to t_cose 1.1.1

### ISSUE THREAD

**Issue by letmaik** [microsoft/scitt-ccf-ledger#100]
This will allow to remove some of the recently added work-around to support Notary header parameters.

This has to be happen in upstream CCF.

**Comment by darracott** [comment]
https://github.com/microsoft/CCF/pull/5016#event-8527660244 updates `t_cose` to v.1.1.1 on the CCF 3.x support branch.  We'll now wait for a new 3.x release. Then we can pull it into SCITT and resolve https://github.com/microsoft/scitt-ccf-ledger/issues/101

**Comment by achamayou** [comment]
@darracott https://github.com/microsoft/CCF/releases/tag/ccf-3.0.6

**Comment by darracott** [comment]
Speedy! Thanks for pointing that out

**Comment by darracott** [comment]
https://github.com/microsoft/scitt-ccf-ledger/pull/122
