### ISSUE TITLE
Inconsistent use of JSON keys snake_case and camelCase in responses

### ISSUE THREAD

**Issue by ivarprudnikov** [microsoft/scitt-ccf-ledger#187]
Inconsistent use of JSON keys: `snake_case` vs `camelCase`

Configuration object is using `snake_case` and is exposed to the user. The `/entries/txIds` endpoint returns a list that has `nextLink`, see renaming logic in JSON https://github.com/microsoft/scitt-ccf-ledger/blob/5cea879c7256a1ce174e3c21d9a25f580ec543aa/app/src/call_types.h#L75-L78 

**Expected behavior**
All JSON keys should use `camelCase` naming convention.

**Comment by achamayou** [comment]
This is consistent with the current state of the spec: https://github.com/ietf-wg-scitt/draft-ietf-scitt-scrapi/blob/main/draft-ietf-scitt-scrapi.md#transparency-configuration, although the layout of the config object has changed and moved to CBOR since.

**Comment by ivarprudnikov** [comment]
Fixed that in the Azure REST API spec but need changes in the code https://github.com/Azure/azure-rest-api-specs/pull/31896

**Comment by ivarprudnikov** [comment]
fixed with in #256
