### ISSUE TITLE
Make `kid` a relative DID URL

### ISSUE THREAD

**Issue by letmaik** [microsoft/scitt-ccf-ledger#22]
The DID/VC community generally used absolute DID URLs as `kid` in VC-JWTs but they are moving to relative to avoid faulty implementations that forget to match that the issuer is a prefix of `kid`. See https://github.com/decentralized-identity/jwt-vc-presentation-profile/blob/main/spec/spec.md#kid-jwt-header for example.

In our code, `kid` is the fragment value, so not an actual relative DID URL. This should be changed to to start with `#` to be consistent and avoid interop issues later on. This aspect is currently underspecified in the SCITT specs.

Note that DID resolution options, if any, are not meant to go into `kid`, so this is a restricted form of relative DID URL only allowing a fragment.

**Comment by plietar** [comment]
> In our code, kid is the fragment value, so not an actual relative DID URL. This should be changed to to start with # to be consistent and avoid interop issues later on. This aspect is currently underspecified in the SCITT specs.

The VC spec you linked says "When relative DID URL is used as a kid, kid only contains a DID fragment", and [`did-core` spec](https://www.w3.org/TR/did-core/#dfn-did-fragments) defines a DID fragment as "The portion of a [DID URL](https://www.w3.org/TR/did-core/#dfn-did-urls) that follows the first hash sign character (#)". From that, my understanding would be that the # symbol should _not_ be included in the kid field, which is what we do today.

**Comment by OR13** [comment]
- https://dev.uniresolver.io/
- https://dev.uniresolver.io/1.0/identifiers/did%3Aion%3AEiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
[- https://github.com/decentralized-identity/jwt-vc-presentation-profile/blob/main/spec/spec.md#wallet-holder
](https://github.com/decentralized-identity/jwt-vc-presentation-profile/blob/main/spec/spec.md#request-object)

```json
 {
    "kid" : "did:ion:EiDX...#key-1",
    "typ" : "JWT",
    "alg" : "EdDSA"
  }.
```

**Comment by OR13** [comment]
Related comment here: https://github.com/w3c/vc-jwt/issues/30#issuecomment-1320610056

**Comment by letmaik** [comment]
@plietar The JWT VC spec I linked isn't precise enough. The term "fragment" is a bit ambiguous, but the fact that it's supposed to be a relative DID URL makes it clear that it should include `#`, because otherwise it wouldn't be a valid relative URI. 
The general idea is that the issuer is a base URL representing the DID doc and the kid is a URL relative to the resolved DID doc.
I know it wastes one extra byte but treating it like a proper relative URL makes it easier to talk about it and allows for future extensions (e.g. parameters), if that should become a thing.

@OR13 That spec should be very clear about the syntax with examples, otherwise people mess it up again.

**Comment by OR13** [comment]
I have some WIP language that attempts to clarify this exact issue here:

- https://transmute-industries.github.io/vc-jws/#producing
- https://transmute-industries.github.io/vc-cose/#producing

The objective is to make obtaining the public key for a signature easy when the `kid` is an absolute or a relative (to iss) DID URL.
