### ISSUE TITLE
Clean up unused functionality

### ISSUE THREAD

**Issue by achamayou** [microsoft/scitt-ccf-ledger#227]
The repository contains a number of SGX-specific and did:web-specific tests. CCF has already dropped support for SGX, and scitt will likely follow shortly (#226), which means that the SGX-specific logic should be removed.

The existing did:web resolver could go one of two ways:

1. A conversion to curl, which can be made available in the confidential containers used to run on SEV-SNP - the associated attestation functionality can be dropped, since it runs in TCB/attested boundary
2. Removal, there are no known users for the did:web functionality, it is not clear whether maintaining this feature is worthwhile.

Regardless of the choice being made, there should be no dependency on did:web for testing, or performance testing, since it is not representative of typical scitt-ccf-ledger use. In other words, it is fine to have tests that exercise did:web but not to have feature tests that rely on did:web to exercise a particular aspect of the ledger.

**Comment by andpiccione** [comment]
Just FYI, we are planning to drop the `did:web` functionality, we have an internal task to track this.

**Comment by vimauro** [comment]
Removed in #231 and #230
