### ISSUE TITLE
Document API endpoints 

### ISSUE THREAD

**Issue by darracott** [microsoft/scitt-ccf-ledger#33]
Endpoints inherited from CCF already have documentation, so there no need to rewrite them but they can be linked or attention can be drawn to important endpoints. 
New scitt-ccf-ledger endpoints are not documented at all yet.

**Comment by letmaik** [comment]
We may want to auto-generate those and also reference the public IETF spec.

**Comment by ivarprudnikov** [comment]
The endpoints (Swagger) are visible under `/app/api` already.
