### ISSUE TITLE
Extend configuration to restrict issuers

### ISSUE THREAD

**Issue by letmaik** [microsoft/scitt-ccf-ledger#8]
Currently, the governance-controlled SCITT-specific configuration allows to set authentication options and the set of allowed signing algorithms. For the non-DID code path (not standard in SCITT at this point), the X.509 CA trust store can be configured as well, which re-uses an existing governance table from CCF.

In addition to that, it should be possible to restrict the set of allowed DID issuers. 

There are a couple of options, but I think at minimum the following should be possible (aka requirements):
- Opt-in to a set of DID methods, out of the ones that are supported. Default to allowing none.
- Allow a specific set of DIDs. Default to allowing all.

I think in the first iteration we shouldn't support regular expressions. It's not clear whether it's needed or whether this is even desirable. I seem to remember that the DID spec says somewhere that you're not supposed to deconstruct a DID and infer relationships etc.

**Comment by ryazhang-microsoft** [comment]
The [PR Extend configuration to restrict issuers](https://github.com/microsoft/scitt-ccf-ledger/pull/13/files) covered requirement "Allow a specific set of DIDs. Default to allowing all".
