### ISSUE TITLE
Expose `did:web` endpoint at `.well-known/did.json`

### ISSUE THREAD

**Issue by letmaik** [microsoft/scitt-ccf-ledger#87]
(Follow-up from https://github.com/microsoft/scitt-ccf-ledger/issues/53)

Currently exposed at `https://<address>/scitt/did.json`.

Depends on https://github.com/microsoft/CCF/issues/4810.

**Comment by achamayou** [comment]
@letmaik fix released in 3.0.6.

**Comment by plietar** [comment]
I don't think it did make it into the release. Somehow https://github.com/microsoft/CCF/pull/4953 has been stuck with "CCF Github CI Expected — Waiting for status to be reported", and no amount of nudging it seems to change anything.

**Comment by plietar** [comment]
Ah right. Thank you. We're not really in a rush to get this in for now, so we'll happily wait for the next release.
